Update everythingto sopport agian SysV init system.

diff --git a/rc.d/init.d/halt b/rc.d/init.d/halt
--- a/rc.d/init.d/halt
+++ b/rc.d/init.d/halt
@@ -8,43 +8,49 @@
 #               Modified for RHS Linux by Damien Neil
 #
 
-NOLOCALE=1
-. /etc/init.d/functions
+NOLOCALE="1"; export NOLOCALE
+source /etc/init.d/functions
+
+if [ "$(readlink /proc/1/exe)" = "/lib/sysvinit/init" ] > /dev/null 2> /dev/null; then
+        /sbin/plymouthd --mode="shutdown"
+        /bin/plymouth --sysinit
+        /bin/plymouth --show-splash
+fi
 
 UMOUNT="umount"
 [ ! -w /etc ] && UMOUNT="umount -n"
 
 halt_crypto() {
     fnval=0
-    while read dst src key; do
-	[ -z "$dst" -o "${dst#\#}" != "$dst" ] && continue
-        if [ -b "/dev/mapper/$dst" ]; then
-            if /sbin/dmsetup info "$dst" | grep -q '^Open count: *0$'; then
-                action $"Stopping disk encryption for $dst" /sbin/cryptsetup remove "$dst"
+    while read -r dst src key; do
+	[ -z "${dst}" ] || [ "${dst#\#}" != "${dst}" ] && continue
+        if [ -b "/dev/mapper/${dst}" ]; then
+            if /sbin/dmsetup info "${dst}" | grep -q '^Open count: *0$'; then
+                action $"Stopping disk encryption for ${dst}" /sbin/cryptsetup remove "${dst}"
             else
                 fnval=1
             fi
         fi
     done < /etc/crypttab
-    return $fnval
+    return ${fnval}
 }
 
 kill_all() {
     local STRING rc
 
     STRING=$1
-    echo -n "$STRING "
+    echo -n "${STRING} "
     shift
     /sbin/killall5 "$@"
     rc=$?
     # Retval: 0: success 1: error 2: no processes found to kill
     if [ "$rc" == 1 ]; then
-        failure $"$STRING"
+        failure $"${STRING}"
     else
-        success $"$STRING"
+        success $"${STRING}"
     fi
     echo
-    return $rc
+    return ${rc}
 }
 
 # See how we were called.
@@ -72,23 +78,27 @@ case "$1" in
 	;;
 esac
 
+if [ "$(readlink /proc/1/exe)" = "/lib/sysvinit/init" ] > /dev/null 2> /dev/null; then
+        /bin/plymouth display-message --text="${message}"
+fi
+
 # Kill all processes.
 [ "${BASH+bash}" = bash ] && enable kill
 
 # Find mdmon pid's and omit killing them
 OMITARGS=
 for i in /dev/md/*.pid; do
-    if [ ! -r "$i" ]; then
+    if [ ! -r "${i}" ]; then
         continue
     fi
-    OMITARGS="$OMITARGS -o $(cat $i)"
+    OMITARGS="${OMITARGS} -o $(cat "${i}")"
 done
 
-kill_all $"Sending all processes the TERM signal..." -15 $OMITARGS
+kill_all $"Sending all processes the TERM signal..." -15 "${OMITARGS}"
 # No need to sleep and kill -9 if no processes to kill were found
 if [ "$?" == 0 ]; then
     sleep 2
-    kill_all $"Sending all processes the KILL signal..." -9 $OMITARGS
+    kill_all $"Sending all processes the KILL signal..." -9 "${OMITARGS}"
 fi
 
 # empty /var/log/boot.log
@@ -110,30 +120,37 @@ action $"Saving random seed: " dd if=/dev/urandom of=/var/lib/random-seed count=
 
 [ -x /sbin/hwclock ] && action $"Syncing hardware clock to system time" /sbin/hwclock --systohc
 
-# Try to unmount tmpfs filesystems to avoid swapping them in.  Ignore failures.
+if [ "$(readlink /proc/1/exe)" = "/lib/sysvinit/init" ] > /dev/null 2> /dev/null; then
+# Tell init to close /run/initctl.
+kill -SIGUSR2 1
+fi
+# Try to unmount tmpfs filesystems to avoid swapping them in. Ignore failures.
 tmpfs=$(awk '$2 ~ /^\/($|proc|dev)/ { next; }
 	     $3 == "tmpfs" { print $2; }' /proc/mounts | sort -r)
-[ -n "$tmpfs" ] && fstab-decode $UMOUNT $tmpfs 2>/dev/null
+[ -n "${tmpfs}" ] && fstab-decode "${UMOUNT}" -f "${tmpfs}" 2>/dev/null
 
 # Turn off swap, then unmount file systems.
-[ -f /proc/swaps ] && SWAPS=$(awk '! /^Filename/ { print $1 }' /proc/swaps)
-if [ -n "$SWAPS" ]; then
-    action $"Turning off swap: " swapoff $SWAPS
-    for dst in $SWAPS; do
-	if [[ "$dst" == /dev/mapper* ]] \
-	    && [ "$(dmsetup status "$dst" | cut -d ' ' -f 3)" = crypt ]; then
-	    backdev=$(/sbin/cryptsetup status "$dst" \
+[ -f "/proc/swaps" ] && SWAPS=$(awk '! /^Filename/ { print $1 }' /proc/swaps)
+if [ -n "${SWAPS}" ]; then
+    action $"Turning off swap: " swapoff "${SWAPS}"
+    for dst in ${SWAPS}; do
+	if [[ "${dst}" == /dev/mapper* ]] \
+	    && [ "$(dmsetup status "${dst}" | cut -d ' ' -f 3)" = crypt ]; then
+	    backdev=$(/sbin/cryptsetup status "${dst}" \
 		| awk '$1 == "device:" { print $2 }')
-	    /sbin/cryptsetup remove "$dst"
+            export backdev
+	    /sbin/cryptsetup remove "${dst}"
 	fi
     done
 fi
 
-[ -x /sbin/quotaoff ] && action $"Turning off quotas: " /sbin/quotaoff -aug
+[ -x "/sbin/quotaoff" ] && action $"Turning off quotas: " /sbin/quotaoff -aug
 
 # Unmount file systems, killing processes if we have to.
 # Unmount loopback stuff first
 __umount_loopback_loop
+
+[ -e "/sys/fs/cgroup/elogind" ] && ${UMOUNT} /sys/fs/cgroup/elogind >/dev/null 2&>1 || :
 
 # Unmount RPC pipe file systems
 __umount_loop '$3 ~ /^rpc_pipefs$/ || $3 ~ /^rpc_svc_gss_pipefs$/ {print $2}' \
@@ -151,9 +168,9 @@ LANG=C __umount_loop '$2 ~ /^\/$|^\/proc|^\/cgroup|^\/sys\/fs\/cgroup|^\/dev/{ne
 	$"Unmounting file systems (retry): " \
 	-f
 
-[ -f /proc/bus/usb/devices ] && $UMOUNT /proc/bus/usb
+[ -f "/proc/bus/usb/devices" ] && ${UMOUNT} /proc/bus/usb
 
-[ -f /etc/crypttab ] && halt_crypto
+[ -f "/etc/crypttab" ] && halt_crypto
 
 # remove the crash indicator flag
 rm -f /.autofsck
@@ -163,29 +180,31 @@ rm -f /.autofsck
 awk '$2 !~ /\/(|dev|proc|selinux|cgroup|sys)$/ && $1 !~ /(^\/dev\/ram|cgroup)/ { print $2 }' \
     /proc/mounts | sort -r | \
   while read line; do
-    fstab-decode $UMOUNT -f $line
+    fstab-decode "${UMOUNT}" -f "${line}" >/dev/null 2&>1 || :
 done
 
-if [ -x /sbin/halt.local ]; then
+if [ -x "/sbin/halt.local" ]; then
    /sbin/halt.local
 fi
 
 # Tell init to re-exec itself.
+if [ "$(readlink /proc/1/exe)" = "/lib/upstart/init" ] > /dev/null 2> /dev/null; then
 kill -TERM 1
+fi
 
 # Remount read only anything that's left mounted.
 # echo $"Remounting remaining filesystems readonly"
 mount | awk '{ print $1,$3 }' | while read dev dir; do
-    fstab-decode mount -n -o ro,remount $dev $dir
+    fstab-decode mount -n -o ro,remount "${dev}" "${dir}" >/dev/null 2&>1 || :
 done
 
 # If we left mdmon's running wait for the raidsets to become clean
-if [ -n "$OMITARGS" ]; then
+if [ -n "${OMITARGS}" ]; then
     mdadm --wait-clean --scan
 fi
 
 # Now halt or reboot.
-echo $"$message"
+echo $"${message}"
 if [ -f /fastboot ]; then
  echo $"On the next boot fsck will be skipped."
 elif [ -f /forcefsck ]; then
@@ -193,23 +212,27 @@ elif [ -f /forcefsck ]; then
 fi
 
 # Shutdown UPS drivers
-if [ "$command" = /sbin/halt ] && [ -f /etc/sysconfig/ups ]; then
-	. /etc/sysconfig/ups
-	if [ -z $POWERDOWNFLAG ]; then
+if [ "${command}" = /sbin/halt ] && [ -f /etc/sysconfig/ups ]; then
+	source /etc/sysconfig/ups
+	if [ -z "${POWERDOWNFLAG}" ]; then
 		POWERDOWNFLAG=/etc/killpower
 	fi
-	if [ "$SERVER" = "yes" ] && [ -f $POWERDOWNFLAG ]; then
+	if [ "$SERVER" = "yes" ] && [ -f "${POWERDOWNFLAG}" ]; then
 		/sbin/upsdrvctl shutdown
 	fi
 fi
 
 # Turn off UPS in powerfail situation
-if [ -x /etc/apcupsd/apccontrol -a -f /etc/apcupsd/powerfail ]; then 
+if [ -x "/etc/apcupsd/apccontrol" ] && [ -f "/etc/apcupsd/powerfail" ]; then 
 	/etc/apcupsd/apccontrol killpower
-fi 
+fi
+
+if [ "$(readlink /proc/1/exe)" = "/lib/sysvinit/init" ] > /dev/null 2> /dev/null; then
+        /bin/plymouth --quit
+fi
 
 # First, try kexec. If that fails, fall back to rebooting the old way.
-[ -n "$kexec_command" ] && $kexec_command -e -x >& /dev/null
+[ -n "${kexec_command}" ] && ${kexec_command} -e -x >& /dev/null
 
 HALTARGS="-d"
 [ "$INIT_HALT" != "HALT" ] && HALTARGS="$HALTARGS -p"
